package com.mns.designsystem.token

import androidx.compose.ui.graphics.Color

/**
 * Fábricas de [MnsColors].
 *
 * Existem para que definir um tema novo não exija escrever 60 cores à mão. Você
 * informa as cores que a marca realmente define (normalmente 2 a 5) e o resto é
 * derivado por interpolação — sempre com um default sensato que você pode
 * sobrescrever campo a campo.
 *
 * ```kotlin
 * val cores = MnsColors.light(
 *     primary = Color(0xFF6255F4),
 *     accent = Color(0xFFA197FF),
 *     background = Color(0xFFF8F8F8),
 * )
 * ```
 */
public fun MnsColors.Companion.light(
    primary: Color,
    onPrimary: Color = primary.contentColorFor(),
    primaryContainer: Color = primary.mixWith(Color.White, 0.88f),
    onPrimaryContainer: Color = primary.mixWith(Color.Black, 0.42f),
    primaryPressed: Color = primary.mixWith(Color.Black, 0.14f),
    primaryDisabled: Color = primary.mixWith(Color.White, 0.62f),

    secondary: Color = primary.mixWith(Color.Black, 0.20f),
    onSecondary: Color = secondary.contentColorFor(),
    secondaryContainer: Color = secondary.mixWith(Color.White, 0.90f),
    onSecondaryContainer: Color = secondary.mixWith(Color.Black, 0.40f),

    accent: Color = primary,
    onAccent: Color = accent.contentColorFor(),
    accentContainer: Color = accent.mixWith(Color.White, 0.90f),
    onAccentContainer: Color = accent.mixWith(Color.Black, 0.45f),

    background: Color = Color(0xFFF7F7F8),
    onBackground: Color = Color(0xFF15151A),
    surface: Color = Color(0xFFFFFFFF),
    onSurface: Color = Color(0xFF15151A),
    surfaceVariant: Color = Color(0xFFF1F1F4),
    onSurfaceVariant: Color = Color(0xFF5B5B66),
    surfaceElevated: Color = Color(0xFFFFFFFF),
    surfaceInverse: Color = Color(0xFF1B1B20),
    onSurfaceInverse: Color = Color(0xFFF5F5F7),

    outline: Color = Color(0xFFDFDFE6),
    outlineVariant: Color = Color(0xFFEDEDF2),
    focusRing: Color = primary,

    success: Color = Color(0xFF16A34A),
    onSuccess: Color = Color(0xFFFFFFFF),
    successContainer: Color = Color(0xFFDCFCE7),
    onSuccessContainer: Color = Color(0xFF14532D),
    warning: Color = Color(0xFFD97706),
    onWarning: Color = Color(0xFFFFFFFF),
    warningContainer: Color = Color(0xFFFEF3C7),
    onWarningContainer: Color = Color(0xFF78350F),
    danger: Color = Color(0xFFDC2626),
    onDanger: Color = Color(0xFFFFFFFF),
    dangerContainer: Color = Color(0xFFFEE2E2),
    onDangerContainer: Color = Color(0xFF7F1D1D),
    info: Color = Color(0xFF2563EB),
    onInfo: Color = Color(0xFFFFFFFF),
    infoContainer: Color = Color(0xFFDBEAFE),
    onInfoContainer: Color = Color(0xFF1E3A8A),

    textPrimary: Color = onSurface,
    textSecondary: Color = Color(0xFF5B5B66),
    textTertiary: Color = Color(0xFF8A8A96),
    textDisabled: Color = Color(0xFFB4B4BE),
    textInverse: Color = Color(0xFFFFFFFF),
    textLink: Color = primary,

    scrim: Color = Color(0xFF000000),
    overlay: Color = Color(0xFF000000),
    shimmerBase: Color = Color(0xFFECECF1),
    shimmerHighlight: Color = Color(0xFFF9F9FC),
    shadow: Color = Color(0xFF0B0B14),
): MnsColors = MnsColors(
    isLight = true,
    primary = primary, onPrimary = onPrimary,
    primaryContainer = primaryContainer, onPrimaryContainer = onPrimaryContainer,
    primaryPressed = primaryPressed, primaryDisabled = primaryDisabled,
    secondary = secondary, onSecondary = onSecondary,
    secondaryContainer = secondaryContainer, onSecondaryContainer = onSecondaryContainer,
    accent = accent, onAccent = onAccent,
    accentContainer = accentContainer, onAccentContainer = onAccentContainer,
    background = background, onBackground = onBackground,
    surface = surface, onSurface = onSurface,
    surfaceVariant = surfaceVariant, onSurfaceVariant = onSurfaceVariant,
    surfaceElevated = surfaceElevated,
    surfaceInverse = surfaceInverse, onSurfaceInverse = onSurfaceInverse,
    outline = outline, outlineVariant = outlineVariant, focusRing = focusRing,
    success = success, onSuccess = onSuccess,
    successContainer = successContainer, onSuccessContainer = onSuccessContainer,
    warning = warning, onWarning = onWarning,
    warningContainer = warningContainer, onWarningContainer = onWarningContainer,
    danger = danger, onDanger = onDanger,
    dangerContainer = dangerContainer, onDangerContainer = onDangerContainer,
    info = info, onInfo = onInfo,
    infoContainer = infoContainer, onInfoContainer = onInfoContainer,
    textPrimary = textPrimary, textSecondary = textSecondary,
    textTertiary = textTertiary, textDisabled = textDisabled,
    textInverse = textInverse, textLink = textLink,
    scrim = scrim, overlay = overlay,
    shimmerBase = shimmerBase, shimmerHighlight = shimmerHighlight,
    shadow = shadow,
)

/** Contraparte escura de [light]. Mesmas regras, defaults invertidos. */
public fun MnsColors.Companion.dark(
    primary: Color,
    onPrimary: Color = primary.contentColorFor(),
    primaryContainer: Color = primary.mixWith(Color.Black, 0.62f),
    onPrimaryContainer: Color = primary.mixWith(Color.White, 0.70f),
    primaryPressed: Color = primary.mixWith(Color.White, 0.16f),
    primaryDisabled: Color = primary.mixWith(Color.Black, 0.55f),

    secondary: Color = primary.mixWith(Color.White, 0.22f),
    onSecondary: Color = secondary.contentColorFor(),
    secondaryContainer: Color = secondary.mixWith(Color.Black, 0.66f),
    onSecondaryContainer: Color = secondary.mixWith(Color.White, 0.68f),

    accent: Color = primary,
    onAccent: Color = accent.contentColorFor(),
    accentContainer: Color = accent.mixWith(Color.Black, 0.66f),
    onAccentContainer: Color = accent.mixWith(Color.White, 0.70f),

    background: Color = Color(0xFF0E0E12),
    onBackground: Color = Color(0xFFF2F2F6),
    surface: Color = Color(0xFF17171D),
    onSurface: Color = Color(0xFFF2F2F6),
    surfaceVariant: Color = Color(0xFF23232B),
    onSurfaceVariant: Color = Color(0xFFA9A9B8),
    surfaceElevated: Color = Color(0xFF1E1E26),
    surfaceInverse: Color = Color(0xFFF2F2F6),
    onSurfaceInverse: Color = Color(0xFF17171D),

    outline: Color = Color(0xFF33333E),
    outlineVariant: Color = Color(0xFF26262F),
    focusRing: Color = primary,

    success: Color = Color(0xFF4ADE80),
    onSuccess: Color = Color(0xFF052E16),
    successContainer: Color = Color(0xFF14532D),
    onSuccessContainer: Color = Color(0xFFBBF7D0),
    warning: Color = Color(0xFFFBBF24),
    onWarning: Color = Color(0xFF451A03),
    warningContainer: Color = Color(0xFF78350F),
    onWarningContainer: Color = Color(0xFFFDE68A),
    danger: Color = Color(0xFFF87171),
    onDanger: Color = Color(0xFF450A0A),
    dangerContainer: Color = Color(0xFF7F1D1D),
    onDangerContainer: Color = Color(0xFFFECACA),
    info: Color = Color(0xFF60A5FA),
    onInfo: Color = Color(0xFF172554),
    infoContainer: Color = Color(0xFF1E3A8A),
    onInfoContainer: Color = Color(0xFFBFDBFE),

    textPrimary: Color = onSurface,
    textSecondary: Color = Color(0xFFA9A9B8),
    textTertiary: Color = Color(0xFF7C7C8C),
    textDisabled: Color = Color(0xFF565663),
    textInverse: Color = Color(0xFF17171D),
    textLink: Color = primary,

    scrim: Color = Color(0xFF000000),
    overlay: Color = Color(0xFF000000),
    shimmerBase: Color = Color(0xFF23232B),
    shimmerHighlight: Color = Color(0xFF32323D),
    shadow: Color = Color(0xFF000000),
): MnsColors = MnsColors(
    isLight = false,
    primary = primary, onPrimary = onPrimary,
    primaryContainer = primaryContainer, onPrimaryContainer = onPrimaryContainer,
    primaryPressed = primaryPressed, primaryDisabled = primaryDisabled,
    secondary = secondary, onSecondary = onSecondary,
    secondaryContainer = secondaryContainer, onSecondaryContainer = onSecondaryContainer,
    accent = accent, onAccent = onAccent,
    accentContainer = accentContainer, onAccentContainer = onAccentContainer,
    background = background, onBackground = onBackground,
    surface = surface, onSurface = onSurface,
    surfaceVariant = surfaceVariant, onSurfaceVariant = onSurfaceVariant,
    surfaceElevated = surfaceElevated,
    surfaceInverse = surfaceInverse, onSurfaceInverse = onSurfaceInverse,
    outline = outline, outlineVariant = outlineVariant, focusRing = focusRing,
    success = success, onSuccess = onSuccess,
    successContainer = successContainer, onSuccessContainer = onSuccessContainer,
    warning = warning, onWarning = onWarning,
    warningContainer = warningContainer, onWarningContainer = onWarningContainer,
    danger = danger, onDanger = onDanger,
    dangerContainer = dangerContainer, onDangerContainer = onDangerContainer,
    info = info, onInfo = onInfo,
    infoContainer = infoContainer, onInfoContainer = onInfoContainer,
    textPrimary = textPrimary, textSecondary = textSecondary,
    textTertiary = textTertiary, textDisabled = textDisabled,
    textInverse = textInverse, textLink = textLink,
    scrim = scrim, overlay = overlay,
    shimmerBase = shimmerBase, shimmerHighlight = shimmerHighlight,
    shadow = shadow,
)
